# Generated by Django 2.0.5 on 2018-06-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capturado',
            name='is_ruteable',
        ),
        migrations.AddField(
            model_name='link',
            name='monitorizar',
            field=models.BooleanField(default=True),
        ),
    ]
