# Generated by Django 2.0.5 on 2018-07-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180604_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='monitorizar',
            new_name='monitorizar_usr',
        ),
        migrations.AddField(
            model_name='link',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
